<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>4 The linear regression model | Half-day Workshop on Phylogenetic Comparative Methods</title>
<meta name="author" content="Simon Joly">
<meta name="description" content="4.1 Theory The linear model has the following form: \[\textbf{y} = \alpha + \beta \textbf{x} + \textbf{e}\] \(\textbf{y}\) is the response (or dependent) variable, \(\textbf{x}\) is the...">
<meta name="generator" content="bookdown 0.41 with bs4_book()">
<meta property="og:title" content="4 The linear regression model | Half-day Workshop on Phylogenetic Comparative Methods">
<meta property="og:type" content="book">
<meta property="og:url" content="https://simjoly.github.io/ComparativeMethods-HalfDayWorkshop/linear-regression.html">
<meta property="og:description" content="4.1 Theory The linear model has the following form: \[\textbf{y} = \alpha + \beta \textbf{x} + \textbf{e}\] \(\textbf{y}\) is the response (or dependent) variable, \(\textbf{x}\) is the...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="4 The linear regression model | Half-day Workshop on Phylogenetic Comparative Methods">
<meta name="twitter:description" content="4.1 Theory The linear model has the following form: \[\textbf{y} = \alpha + \beta \textbf{x} + \textbf{e}\] \(\textbf{y}\) is the response (or dependent) variable, \(\textbf{x}\) is the...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.7.0/transition.js"></script><script src="libs/bs3compat-0.7.0/tabs.js"></script><script src="libs/bs3compat-0.7.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet">
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
          margin-bottom: 0em;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Half-day Workshop on Phylogenetic Comparative Methods</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html"><span class="header-section-number">1</span> About</a></li>
<li><a class="" href="before.html"><span class="header-section-number">2</span> Ahead of the workshop</a></li>
<li><a class="" href="intro.html"><span class="header-section-number">3</span> An introduction to Phylogenetic Comparative Methods</a></li>
<li><a class="active" href="linear-regression.html"><span class="header-section-number">4</span> The linear regression model</a></li>
<li><a class="" href="pgls.html"><span class="header-section-number">5</span> Phylogenetic generalized least squares (PGLS)</a></li>
<li><a class="" href="pic.html"><span class="header-section-number">6</span> Phylogenetic Independent Contrasts</a></li>
<li><a class="" href="relaxing-the-assumption-that-residuals-need-to-be-perfectly-phylogenetically-correlated.html"><span class="header-section-number">7</span> Relaxing the assumption that residuals need to be perfectly phylogenetically correlated</a></li>
<li><a class="" href="phylogenetic-anova.html"><span class="header-section-number">8</span> Phylogenetic ANOVA</a></li>
<li><a class="" href="model-testing.html"><span class="header-section-number">9</span> Model testing</a></li>
<li><a class="" href="when-should-we-use-comparative-methods.html"><span class="header-section-number">10</span> When should we use comparative methods?</a></li>
<li><a class="" href="a-final-word-the-problem-of-replication.html"><span class="header-section-number">11</span> A final word: the problem of replication</a></li>
<li><a class="" href="BM-model.html"><span class="header-section-number">12</span> The Brownian Motion (BM) model</a></li>
<li><a class="" href="further-readings.html"><span class="header-section-number">13</span> Further readings</a></li>
<li><a class="" href="trees.html"><span class="header-section-number">14</span> Introduction to phylogenies in R</a></li>
<li><a class="" href="solutions.html"><span class="header-section-number">15</span> Solutions to the challenges</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="linear-regression" class="section level1" number="4">
<h1>
<span class="header-section-number">4</span> The linear regression model<a class="anchor" aria-label="anchor" href="#linear-regression"><i class="fas fa-link"></i></a>
</h1>
<div id="theory" class="section level2" number="4.1">
<h2>
<span class="header-section-number">4.1</span> Theory<a class="anchor" aria-label="anchor" href="#theory"><i class="fas fa-link"></i></a>
</h2>
<p>The linear model has the following form:</p>
<p><span class="math display">\[\textbf{y} = \alpha + \beta \textbf{x} + \textbf{e}\]</span></p>
<p><span class="math inline">\(\textbf{y}\)</span> is the response (or dependent) variable, <span class="math inline">\(\textbf{x}\)</span> is the explanatory (or independent) variable, and <span class="math inline">\(\textbf{e}\)</span> represent the residuals or in other words the variation not explained by the model. For a simple linear regression model, this represents the distance between the observations (i.e., the real data) and the regression line (i.e., the prediction of the model) along the <span class="math inline">\(y\)</span> axis. The parameters <span class="math inline">\(\alpha\)</span> represents the intercept, which is the <span class="math inline">\(y\)</span> value where the regression line crosses the <span class="math inline">\(y\)</span> axis, whereas the parameter <span class="math inline">\(\beta\)</span> represent the slope of the line. In practice, you take a sample of size <span class="math inline">\(N\)</span> and you get estimates <span class="math inline">\(\hat{\alpha}\)</span> and <span class="math inline">\(\hat{\beta}\)</span> for the intercept and the slope, respectively. When the linear regression is fitted using ordinary least squares (OLS), the residuals <span class="math inline">\(\textbf{e}\)</span> are assumed to be normally distributed with an expectation <span class="math inline">\(0\)</span> and variance <span class="math inline">\(\sigma^2\)</span>. In mathematical terms, <span class="math inline">\(\textbf{e} \sim N(0,\sigma^2)\)</span>.</p>
<p>Obtaining reliable estimates with a linear regression implies that the data meets several assumptions, amongst which are normality, homogeneity, fixed <span class="math inline">\(X\)</span>, independence, and correct model specification. We won’t review all these here, but we will focus on one that is often violated when the data are phylogenetically structured, which is <strong>independence</strong>. This assumption is important as a lack of independence invalidates important tests such as the F-test and the t-test.</p>
<p>You get a violation of independence when the <span class="math inline">\(\textbf{y}_i\)</span> value at <span class="math inline">\(\textbf{x}_i\)</span> is influenced by other <span class="math inline">\(\textbf{x}_i\)</span>. Obviously, this can happen with phylogenetically structured data as a response variable is be more likely to react similarly in closely related species because they share many characters by decent. In other words, the <span class="math inline">\(y\)</span> value for a species in not completely independent from the <span class="math inline">\(y\)</span> value of a closely related species: their <span class="math inline">\(y\)</span> are correlated. We’ll illustrate this in an example below.</p>
</div>
<div id="practice" class="section level2" number="4.2">
<h2>
<span class="header-section-number">4.2</span> Practice<a class="anchor" aria-label="anchor" href="#practice"><i class="fas fa-link"></i></a>
</h2>
<p>To provide pratical examples in this workshop, we will use a dataset of tree functional traits from the province of Quebec <span class="citation">(<a href="references.html#ref-paquette2015explaining">Paquette, Joly, and Messier 2015</a>)</span>. The dataset consists in a number of plant functional traits and in a molecular phylogeny built using the plant barcode markers <em>rbc</em>L and <em>mat</em>K. The dataset you need to run the examples are already in the /data/ folder of the github repository. However, you can also download them by clicking on the links below.</p>
<p><a href="https://simjoly.github.io/ComparativeMethods-HalfDayWorkshop/data/seedplants.tre">seedplants.tre</a></p>
<p><a href="https://simjoly.github.io/ComparativeMethods-HalfDayWorkshop/data/seedplants.csv">seedplants.csv</a></p>
<p>Before analysing the data, we will start by opening the data and the phylogenetic tree and clean them to keep only the species present in both the tree and the trait table. This is necessary because some additional species were included in the phylogenetic tree analysis.</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">require</a></span><span class="op">(</span><span class="va"><a href="https://github.com/emmanuelparadis/ape">ape</a></span><span class="op">)</span></span>
<span><span class="co"># Open the documents; it assumes that you are in the main directory of the workshop folder</span></span>
<span><span class="va">seedplantstree</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/ape/man/read.nexus.html">read.nexus</a></span><span class="op">(</span><span class="st">"./data/seedplants.tre"</span><span class="op">)</span></span>
<span><span class="va">seedplantsdata</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv2</a></span><span class="op">(</span><span class="st">"./data/seedplants.csv"</span><span class="op">)</span></span>
<span><span class="co"># Remove species for which we don't have complete data</span></span>
<span><span class="va">seedplantsdata</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/na.fail.html">na.omit</a></span><span class="op">(</span><span class="va">seedplantsdata</span><span class="op">)</span></span>
<span><span class="co"># Remove species in the tree that are not in the data matrix</span></span>
<span><span class="va">species.to.exclude</span> <span class="op">&lt;-</span> <span class="va">seedplantstree</span><span class="op">$</span><span class="va">tip.label</span><span class="op">[</span><span class="op">!</span><span class="op">(</span><span class="va">seedplantstree</span><span class="op">$</span><span class="va">tip.label</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="va">seedplantsdata</span><span class="op">$</span><span class="va">Code</span><span class="op">)</span><span class="op">]</span></span>
<span><span class="va">seedplantstree</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/ape/man/drop.tip.html">drop.tip</a></span><span class="op">(</span><span class="va">seedplantstree</span>,<span class="va">species.to.exclude</span><span class="op">)</span></span>
<span><span class="co"># Remove unnecessary object</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/rm.html">rm</a></span><span class="op">(</span><span class="va">species.to.exclude</span><span class="op">)</span></span>
<span><span class="co"># Order the tree to make it nicer when plotting</span></span>
<span><span class="va">seedplantstree</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/ape/man/ladderize.html">ladderize</a></span><span class="op">(</span><span class="va">seedplantstree</span>, right <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="co"># Now let's look at the tree</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">seedplantstree</span>,cex<span class="op">=</span><span class="fl">0.4</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="pcm-workshop_files/figure-html/Open_seed_plant_data-1.png" width="672" style="display: block; margin: auto;"></div>
<p>Now, we can have a look at the data, and then order the plant trait to be in the same order as the species in the tree.</p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Here is what the loaded data looks like</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">seedplantsdata</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   Code       Species.name Occurrence maxH   Wd    Sm Shade    N
## 1 ABBA     Abies balsamea       7759   25 0.34   7.6   5.0 1.66
## 2 ACNE       Acer negundo          0   20 0.44  34.0   3.5 2.50
## 3 ACNI        Acer nigrum          1   30 0.52  65.0   3.0 1.83
## 4 ACPE Acer pensylvanicum        665   10 0.44  41.0   3.5 2.22
## 5 ACPL   Acer platanoides          0   15 0.51 172.0   4.2 1.99
## 6 ACRU        Acer rubrum       3669   25 0.49  20.0   3.4 1.91</code></pre>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Name the rows of the data.frame with the species codes used as tree labels </span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">seedplantsdata</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="va">seedplantsdata</span><span class="op">$</span><span class="va">Code</span></span>
<span><span class="co"># Order the data in the same order as the tip.label of the tree. In the present </span></span>
<span><span class="co">#  example, this was already the case, but it is an important step for </span></span>
<span><span class="co">#  any analysis.</span></span>
<span><span class="va">seedplantsdata</span> <span class="op">&lt;-</span> <span class="va">seedplantsdata</span><span class="op">[</span><span class="va">seedplantstree</span><span class="op">$</span><span class="va">tip.label</span>,<span class="op">]</span></span></code></pre></div>
<p>Now that the data is ready, let’s fit a linear model and try to explain shade tolerance (Shade) of trees using wood density (Wd). In R, a very simple way to do a regression is to use the function ‘lm’, which stands for linear model. To fit a linear model, you need to tell the <code>lm</code> function which variable is the response variable and which one is the explanatory variable. This is done using formulas in the form <code>Shade ~ Wd</code>. The variable at the left of the tilde (‘~’) is the response variable (<code>Shade</code>) whereas the explanatory variale (1 or more) are at the right of the tilde.</p>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Fit a linear model using Ordinary Least Squares (OLS)</span></span>
<span><span class="va">shade.lm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Shade</span> <span class="op">~</span> <span class="va">Wd</span>, data <span class="op">=</span> <span class="va">seedplantsdata</span><span class="op">)</span></span>
<span><span class="co"># Print the results</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">shade.lm</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Shade ~ Wd, data = seedplantsdata)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.87120 -1.02501  0.05628  0.70132  2.38261 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)   2.0010     0.7501   2.668    0.010 *
## Wd            1.8130     1.5676   1.157    0.252  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.146 on 55 degrees of freedom
## Multiple R-squared:  0.02374,    Adjusted R-squared:  0.005992 
## F-statistic: 1.338 on 1 and 55 DF,  p-value: 0.2525</code></pre>
<p>You can see that the slope estimate (here the parameter <code>Wd</code>) is 1.81 and that is not significant (<span class="math inline">\(p\)</span>=0.252). The standard descriptive plots obtained with <code>plot(shade.lm)</code> show that there is slightly greater variation in the residuals for low fitted values, but these are not extreme. However, another way that the assumption of independence can be violated is if the residuals are phylogenetically correlated. One way to test this is to plot the residuals at the tips of the phylogeny. Let’s see what this gives.</p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Extract the residuals</span></span>
<span><span class="va">shade.res</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">shade.lm</span><span class="op">)</span></span>
<span></span>
<span><span class="co">#</span></span>
<span><span class="co"># Plot the residuals beside the phylogeny</span></span>
<span></span>
<span><span class="co"># The following command changes the graphical parameters for nicer tree output</span></span>
<span><span class="va">op</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mar<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">1</span>,<span class="fl">1</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co"># Vector of colors for the tree plotting</span></span>
<span><span class="va">cols</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"#7570b3"</span>,<span class="st">"#d95f02"</span><span class="op">)</span></span>
<span><span class="co"># The next three commands will plot the tree, then circles that reflect </span></span>
<span><span class="co">#  the residuals values at the tips of the tree, and will finally</span></span>
<span><span class="co">#  add a legend.</span></span>
<span><span class="co"># The plot command plots the tree and leaves some space to plot the </span></span>
<span><span class="co">#  residuals at the tips with the 'label.offset=0.01' option</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">seedplantstree</span>,type<span class="op">=</span><span class="st">"p"</span>,<span class="cn">TRUE</span>,label.offset<span class="op">=</span><span class="fl">0.01</span>,cex<span class="op">=</span><span class="fl">0.5</span>,no.margin<span class="op">=</span><span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="co"># The next command plots the residuals. the 'bg' option is for the background color.</span></span>
<span><span class="co">#  If the residuals are greater than 0 (shade.res&gt;0), it will print the first color</span></span>
<span><span class="co">#  (1) of the 'cols' array and if it is below zero, it prints the second color (2). </span></span>
<span><span class="co">#  The the size of the circle (the 'cex' option) is relative to the absolute value </span></span>
<span><span class="co">#  of the residuals (abs(shade.res). To plot other values, just replace the </span></span>
<span><span class="co">#  'shade.res' vector by another one.</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/ape/man/nodelabels.html">tiplabels</a></span><span class="op">(</span>pch<span class="op">=</span><span class="fl">21</span>,bg<span class="op">=</span><span class="va">cols</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">shade.res</span><span class="op">&gt;</span><span class="fl">0</span>,<span class="fl">1</span>,<span class="fl">2</span><span class="op">)</span><span class="op">]</span>,col<span class="op">=</span><span class="st">"black"</span>,cex<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">shade.res</span><span class="op">)</span>,adj<span class="op">=</span><span class="fl">0.505</span><span class="op">)</span></span>
<span><span class="co"># Print the legend</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/legend.html">legend</a></span><span class="op">(</span><span class="st">"topleft"</span>,legend<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"-2"</span>,<span class="st">"-1"</span>,<span class="st">"0"</span>,<span class="st">"1"</span>,<span class="st">"2"</span><span class="op">)</span>,pch<span class="op">=</span><span class="fl">21</span>,</span>
<span>       pt.bg<span class="op">=</span><span class="va">cols</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">1</span>,<span class="fl">1</span>,<span class="fl">2</span>,<span class="fl">2</span><span class="op">)</span><span class="op">]</span>,bty<span class="op">=</span><span class="st">"n"</span>,</span>
<span>       text.col<span class="op">=</span><span class="st">"gray32"</span>,cex<span class="op">=</span><span class="fl">0.8</span>,pt.cex<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>,<span class="fl">1</span>,<span class="fl">0.1</span>,<span class="fl">1</span>,<span class="fl">2</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="pcm-workshop_files/figure-html/Residuals%20of%20lm%20on%20phylogeny-1.png" width="672" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Reset graphical parameters to defaults</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span><span class="va">op</span><span class="op">)</span> </span></code></pre></div>
<p>You can see that in several cases, closely related species tend to have similar residuals (they are of the same color, which means that they are of the same side of the regression slope). This is problematic. Indeed, it shows that the assumption of independence of the ordinary least squares (OLS) regression no longer holds and the statistical tests for the null hypotheses are no longer valid. We will see next how phylogenetic generalized least squares can correct this.</p>
</div>
<div id="challenge-1" class="section level2" number="4.3">
<h2>
<span class="header-section-number">4.3</span> Challenge 1<a class="anchor" aria-label="anchor" href="#challenge-1"><i class="fas fa-link"></i></a>
</h2>
<p>In the <code>seedplantsdata</code> data frame, there were many different traits. Try to fit a regression of tree shade tolerance (<code>shade</code>) on the seed mass (<code>Sm</code>). In other words, test if shade tolerance can be explained by the seed mass of the trees. Then, try to see if the residuals are phylogenetically correlated.</p>

</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="intro.html"><span class="header-section-number">3</span> An introduction to Phylogenetic Comparative Methods</a></div>
<div class="next"><a href="pgls.html"><span class="header-section-number">5</span> Phylogenetic generalized least squares (PGLS)</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#linear-regression"><span class="header-section-number">4</span> The linear regression model</a></li>
<li><a class="nav-link" href="#theory"><span class="header-section-number">4.1</span> Theory</a></li>
<li><a class="nav-link" href="#practice"><span class="header-section-number">4.2</span> Practice</a></li>
<li><a class="nav-link" href="#challenge-1"><span class="header-section-number">4.3</span> Challenge 1</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Half-day Workshop on Phylogenetic Comparative Methods</strong>" was written by Simon Joly. It was last built on 2024-11-09.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
