<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5 Phylogenetic generalized least squares (PGLS) | Half-day Workshop on Phylogenetic Comparative Methods</title>
  <meta name="description" content="This is a book that contains information on a half-day introductoray workshop on Phylogenetic Comparative Methods" />
  <meta name="generator" content="bookdown 0.29 and GitBook 2.6.7" />

  <meta property="og:title" content="5 Phylogenetic generalized least squares (PGLS) | Half-day Workshop on Phylogenetic Comparative Methods" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a book that contains information on a half-day introductoray workshop on Phylogenetic Comparative Methods" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5 Phylogenetic generalized least squares (PGLS) | Half-day Workshop on Phylogenetic Comparative Methods" />
  
  <meta name="twitter:description" content="This is a book that contains information on a half-day introductoray workshop on Phylogenetic Comparative Methods" />
  

<meta name="author" content="Simon Joly" />


<meta name="date" content="2023-02-20" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="linear-regression.html"/>
<link rel="next" href="pic.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">PCM workshop</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> About</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#useful-resources"><i class="fa fa-check"></i><b>1.1</b> Useful resources</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#source"><i class="fa fa-check"></i><b>1.2</b> Source</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#disclaimer"><i class="fa fa-check"></i><b>1.3</b> Disclaimer</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="before.html"><a href="before.html"><i class="fa fa-check"></i><b>2</b> Ahead of the workshop</a>
<ul>
<li class="chapter" data-level="2.1" data-path="before.html"><a href="before.html#install-r-and-the-required-packages"><i class="fa fa-check"></i><b>2.1</b> Install R and the required packages</a></li>
<li class="chapter" data-level="2.2" data-path="before.html"><a href="before.html#download"><i class="fa fa-check"></i><b>2.2</b> Downloading the data</a></li>
<li class="chapter" data-level="2.3" data-path="before.html"><a href="before.html#get-acquainted-with-phylogenetic-trees-in-r"><i class="fa fa-check"></i><b>2.3</b> Get acquainted with phylogenetic trees in R</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>3</b> An introduction to Phylogenetic Comparative Methods</a></li>
<li class="chapter" data-level="4" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i><b>4</b> The linear regression model</a>
<ul>
<li class="chapter" data-level="4.1" data-path="linear-regression.html"><a href="linear-regression.html#theory"><i class="fa fa-check"></i><b>4.1</b> Theory</a></li>
<li class="chapter" data-level="4.2" data-path="linear-regression.html"><a href="linear-regression.html#practice"><i class="fa fa-check"></i><b>4.2</b> Practice</a></li>
<li class="chapter" data-level="4.3" data-path="linear-regression.html"><a href="linear-regression.html#challenge-1"><i class="fa fa-check"></i><b>4.3</b> Challenge 1</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="pgls.html"><a href="pgls.html"><i class="fa fa-check"></i><b>5</b> Phylogenetic generalized least squares (PGLS)</a>
<ul>
<li class="chapter" data-level="5.1" data-path="pgls.html"><a href="pgls.html#theory-1"><i class="fa fa-check"></i><b>5.1</b> Theory</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="pgls.html"><a href="pgls.html#phylogenetic-correlation-structure"><i class="fa fa-check"></i><b>5.1.1</b> Phylogenetic correlation structure</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="pgls.html"><a href="pgls.html#challenge-2"><i class="fa fa-check"></i><b>5.2</b> Challenge 2</a></li>
<li class="chapter" data-level="5.3" data-path="pgls.html"><a href="pgls.html#practicals"><i class="fa fa-check"></i><b>5.3</b> Practicals</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="pgls.html"><a href="pgls.html#other-correlation-structures"><i class="fa fa-check"></i><b>5.3.1</b> Other correlation structures</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="pgls.html"><a href="pgls.html#challenge-3"><i class="fa fa-check"></i><b>5.4</b> Challenge 3</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="pic.html"><a href="pic.html"><i class="fa fa-check"></i><b>6</b> Phylogenetic Independent Contrasts</a></li>
<li class="chapter" data-level="7" data-path="relaxing-the-assumption-that-residuals-need-to-be-perfectly-phylogenetically-correlated.html"><a href="relaxing-the-assumption-that-residuals-need-to-be-perfectly-phylogenetically-correlated.html"><i class="fa fa-check"></i><b>7</b> Relaxing the assumption that residuals need to be perfectly phylogenetically correlated</a>
<ul>
<li class="chapter" data-level="7.1" data-path="relaxing-the-assumption-that-residuals-need-to-be-perfectly-phylogenetically-correlated.html"><a href="relaxing-the-assumption-that-residuals-need-to-be-perfectly-phylogenetically-correlated.html#theory-pagels-correlation-structure"><i class="fa fa-check"></i><b>7.1</b> Theory: Pagel’s correlation structure</a></li>
<li class="chapter" data-level="7.2" data-path="relaxing-the-assumption-that-residuals-need-to-be-perfectly-phylogenetically-correlated.html"><a href="relaxing-the-assumption-that-residuals-need-to-be-perfectly-phylogenetically-correlated.html#practicals-1"><i class="fa fa-check"></i><b>7.2</b> Practicals</a></li>
<li class="chapter" data-level="7.3" data-path="relaxing-the-assumption-that-residuals-need-to-be-perfectly-phylogenetically-correlated.html"><a href="relaxing-the-assumption-that-residuals-need-to-be-perfectly-phylogenetically-correlated.html#challenge-4"><i class="fa fa-check"></i><b>7.3</b> Challenge 4</a></li>
<li class="chapter" data-level="7.4" data-path="relaxing-the-assumption-that-residuals-need-to-be-perfectly-phylogenetically-correlated.html"><a href="relaxing-the-assumption-that-residuals-need-to-be-perfectly-phylogenetically-correlated.html#other-correlation-structures-or-evolutionary-models"><i class="fa fa-check"></i><b>7.4</b> Other correlation structures (or evolutionary models)</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="phylogenetic-anova.html"><a href="phylogenetic-anova.html"><i class="fa fa-check"></i><b>8</b> Phylogenetic ANOVA</a></li>
<li class="chapter" data-level="9" data-path="model-testing.html"><a href="model-testing.html"><i class="fa fa-check"></i><b>9</b> Model testing</a></li>
<li class="chapter" data-level="10" data-path="when-should-we-use-comparative-methods.html"><a href="when-should-we-use-comparative-methods.html"><i class="fa fa-check"></i><b>10</b> When should we use comparative methods?</a></li>
<li class="chapter" data-level="11" data-path="a-final-word-the-problem-of-replication.html"><a href="a-final-word-the-problem-of-replication.html"><i class="fa fa-check"></i><b>11</b> A final word: the problem of replication</a></li>
<li class="chapter" data-level="12" data-path="BM-model.html"><a href="BM-model.html"><i class="fa fa-check"></i><b>12</b> The Brownian Motion (BM) model</a></li>
<li class="chapter" data-level="13" data-path="further-readings.html"><a href="further-readings.html"><i class="fa fa-check"></i><b>13</b> Further readings</a></li>
<li class="chapter" data-level="14" data-path="trees.html"><a href="trees.html"><i class="fa fa-check"></i><b>14</b> Introduction to phylogenies in R</a>
<ul>
<li class="chapter" data-level="14.1" data-path="trees.html"><a href="trees.html#importing-and-plotting-trees"><i class="fa fa-check"></i><b>14.1</b> Importing and plotting trees</a>
<ul>
<li class="chapter" data-level="14.1.1" data-path="trees.html"><a href="trees.html#simulate-a-tree"><i class="fa fa-check"></i><b>14.1.1</b> Simulate a tree</a></li>
<li class="chapter" data-level="14.1.2" data-path="trees.html"><a href="trees.html#simulating-characters"><i class="fa fa-check"></i><b>14.1.2</b> Simulating characters</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="trees.html"><a href="trees.html#import-data-into-r"><i class="fa fa-check"></i><b>14.2</b> Import data into R</a></li>
<li class="chapter" data-level="14.3" data-path="trees.html"><a href="trees.html#plot-trees"><i class="fa fa-check"></i><b>14.3</b> Plot trees</a></li>
<li class="chapter" data-level="14.4" data-path="trees.html"><a href="trees.html#handling-multiple-trees"><i class="fa fa-check"></i><b>14.4</b> Handling multiple trees</a></li>
<li class="chapter" data-level="14.5" data-path="trees.html"><a href="trees.html#manipulating-trees"><i class="fa fa-check"></i><b>14.5</b> Manipulating trees</a>
<ul>
<li class="chapter" data-level="14.5.1" data-path="trees.html"><a href="trees.html#drop-tips"><i class="fa fa-check"></i><b>14.5.1</b> Drop tips</a></li>
<li class="chapter" data-level="14.5.2" data-path="trees.html"><a href="trees.html#reroot-trees"><i class="fa fa-check"></i><b>14.5.2</b> Reroot trees</a></li>
<li class="chapter" data-level="14.5.3" data-path="trees.html"><a href="trees.html#get-cophenetic-distances"><i class="fa fa-check"></i><b>14.5.3</b> Get cophenetic distances</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="solutions.html"><a href="solutions.html"><i class="fa fa-check"></i><b>15</b> Solutions to the challenges</a>
<ul>
<li class="chapter" data-level="15.1" data-path="solutions.html"><a href="solutions.html#challenge-1-1"><i class="fa fa-check"></i><b>15.1</b> Challenge 1</a></li>
<li class="chapter" data-level="15.2" data-path="solutions.html"><a href="solutions.html#challenge-2-1"><i class="fa fa-check"></i><b>15.2</b> Challenge 2</a></li>
<li class="chapter" data-level="15.3" data-path="solutions.html"><a href="solutions.html#challenge-3-1"><i class="fa fa-check"></i><b>15.3</b> Challenge 3</a></li>
<li class="chapter" data-level="15.4" data-path="solutions.html"><a href="solutions.html#challenge-4-1"><i class="fa fa-check"></i><b>15.4</b> Challenge 4</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Half-day Workshop on Phylogenetic Comparative Methods</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="pgls" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">5</span> Phylogenetic generalized least squares (PGLS)<a href="pgls.html#pgls" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="theory-1" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Theory<a href="pgls.html#theory-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Phylogenetic generalized least squares (PGLS) is just a specific application of the broader method called generalized least squares (GLS). Generalized least squares relax the assumption that the error of the linear model has to be uncorrelated. They allow the user to specify the structure of that residual correlation. This is used, for instance, to correct for spatial correlation, time series, or phylogenetic correlation.</p>
<p>GLS have the same structure as Ordinary Least Squares (OLS):</p>
<p><span class="math display">\[\textbf{y} = \alpha + \beta \textbf{x} + \textbf{e}\]</span></p>
<p>The only difference is that the residuals are correlated with each other according to a correlation structure <span class="math inline">\(\textbf{C}\)</span>:</p>
<p><span class="math display">\[\textbf{e} \sim N(0,\sigma^2\textbf{C})\]</span></p>
<p>Here, <span class="math inline">\(\textbf{C}\)</span> is a correlation matrix that describes how the residuals are correlated with each other. To be able to account for phylogenetic relationships in a PGLS, we thus need to be able to express the phylogenetic relationships in the form of a correlation matrix.</p>
<div id="phylogenetic-correlation-structure" class="section level3 hasAnchor" number="5.1.1">
<h3><span class="header-section-number">5.1.1</span> Phylogenetic correlation structure<a href="pgls.html#phylogenetic-correlation-structure" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Phylogenetic relationships can be described using a correlation structure. Below, you have phylogenetic tree with branch lengths indicated above the branches.</p>
<p><img src="pcm-workshop_files/figure-html/phylogenetic%20tree%20example-1.png" width="288" style="display: block; margin: auto auto auto 0;" /></p>
<p>Now, this tree can be perfectly represented by a variance-covariance matrix.</p>
<pre><code>##      a    b    c    c    d
## a 1.05 0.90 0.50 0.00 0.00
## b 0.90 1.05 0.50 0.00 0.00
## c 0.50 0.50 1.05 0.00 0.00
## c 0.00 0.00 0.00 1.05 0.80
## d 0.00 0.00 0.00 0.80 1.05</code></pre>
<p>The diagonal elements of the matrix are the species variances; these numbers represent the total distance from the root of the tree to the tips. It determines how much the tips have evolved from the root. The off-diagonal elements are the covariances between the species. They indicate the proportion of the time that the species have evolved together. This corresponds to the length of the branches that two species share, starting from the root of the tree. For instance, species <span class="math inline">\(a\)</span> and <span class="math inline">\(c\)</span> have shared a common history for 0.5 units of time; hence they have a covariance of 0.5. The greater the covariance, the longer the two species have shared the same evolutionary history.</p>
<p>If all the variation among species was due to phylogeny and none to selection, then this variance-covariance matrix would represent the expectation of how much all species would be similar to the other species.</p>
<blockquote>
<p>Note that all the tips are equidistant from the root. When trees have this property, they are said to be <strong><em>ultrametric</em></strong>. Most phylogenetic comparative methods require the trees to be ultrametric, although there are sometimes ways to relax this assumption. If you do not have an ultrametric tree, it is possible to make it ultrametric using the function <code>chronopl</code> of the <code>ape</code> package. But ideally, it is better to use a phylogenetic method that directly reconstruct ultrametric trees.</p>
</blockquote>
<p>The variance-covariance matrix of a phylogenetic tree can be obtained from a tree using the function <code>vcv</code> from the <code>ape</code> package.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="pgls.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># &#39;atree&#39; corresponds to the phylogenetic tree shown above in newick format</span></span>
<span id="cb16-2"><a href="pgls.html#cb16-2" aria-hidden="true" tabindex="-1"></a>atree <span class="ot">&lt;-</span> <span class="st">&quot;(((a:0.15,b:0.15):0.4,c:0.55):0.5,(c:0.25,d:0.25):0.8);&quot;</span></span>
<span id="cb16-3"><a href="pgls.html#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Let&#39;s now read this tree and store it as a phylogenetic tree object in R</span></span>
<span id="cb16-4"><a href="pgls.html#cb16-4" aria-hidden="true" tabindex="-1"></a>atree <span class="ot">&lt;-</span> <span class="fu">read.tree</span>(<span class="at">text=</span>atree)</span>
<span id="cb16-5"><a href="pgls.html#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the tree</span></span>
<span id="cb16-6"><a href="pgls.html#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(atree)</span></code></pre></div>
<p><img src="pcm-workshop_files/figure-html/vcv%20function-1.png" width="672" /></p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="pgls.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the variance-covariance matrix</span></span>
<span id="cb17-2"><a href="pgls.html#cb17-2" aria-hidden="true" tabindex="-1"></a>varcovar <span class="ot">&lt;-</span> <span class="fu">vcv</span>(atree)</span>
<span id="cb17-3"><a href="pgls.html#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the variance-covariance matrix</span></span>
<span id="cb17-4"><a href="pgls.html#cb17-4" aria-hidden="true" tabindex="-1"></a>varcovar</span></code></pre></div>
<pre><code>##      a    b    c    c    d
## a 1.05 0.90 0.50 0.00 0.00
## b 0.90 1.05 0.50 0.00 0.00
## c 0.50 0.50 1.05 0.00 0.00
## c 0.00 0.00 0.00 1.05 0.80
## d 0.00 0.00 0.00 0.80 1.05</code></pre>
<p>This is great, but we mentioned above that it is a correlation matric that we need in a GLS to account for the correlation in the residuals. To obtain a correlation matrix from the variance-covariance matrix shown above, you only need to divide the variance-covariance matrix by the length of the tree, or the distance from the root to the tips. It can also be obtained using the R function <code>cov2cor</code>.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="pgls.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the covariance matrix to a correlation matrix</span></span>
<span id="cb19-2"><a href="pgls.html#cb19-2" aria-hidden="true" tabindex="-1"></a>corrmat <span class="ot">&lt;-</span> <span class="fu">cov2cor</span>(varcovar)</span>
<span id="cb19-3"><a href="pgls.html#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the matrix, rounding the numbers to three decimals</span></span>
<span id="cb19-4"><a href="pgls.html#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(corrmat,<span class="dv">3</span>)</span></code></pre></div>
<pre><code>##       a     b     c     c     d
## a 1.000 0.857 0.476 0.000 0.000
## b 0.857 1.000 0.476 0.000 0.000
## c 0.476 0.476 1.000 0.000 0.000
## c 0.000 0.000 0.000 1.000 0.762
## d 0.000 0.000 0.000 0.762 1.000</code></pre>
<p>Now, the diagonal elements equal to 1, indicating that the species are perfectly correlated to themselves. Note that it is also possible to obtain directly the correlation matrix from the function <code>vcv</code> by using the <code>corr=TRUE</code> option.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="pgls.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtaining a correlation matrix using the &#39;vcv&#39; function</span></span>
<span id="cb21-2"><a href="pgls.html#cb21-2" aria-hidden="true" tabindex="-1"></a>corrmat <span class="ot">&lt;-</span> <span class="fu">vcv</span>(atree,<span class="at">corr=</span><span class="cn">TRUE</span>)</span>
<span id="cb21-3"><a href="pgls.html#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(corrmat,<span class="dv">3</span>)</span></code></pre></div>
<pre><code>##       a     b     c     c     d
## a 1.000 0.857 0.476 0.000 0.000
## b 0.857 1.000 0.476 0.000 0.000
## c 0.476 0.476 1.000 0.000 0.000
## c 0.000 0.000 0.000 1.000 0.762
## d 0.000 0.000 0.000 0.762 1.000</code></pre>
<p>Now that we know how to obtain a correlation matrix from a phylogenetic tree, we are ready to run a PGLS.</p>
</div>
</div>
<div id="challenge-2" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> Challenge 2<a href="pgls.html#challenge-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Can you get the covariance matrix and the correlation matrix for the seed plants phylogenetic tree from the example above (<code>seedplantstree</code>)?</p>
</div>
<div id="practicals" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Practicals<a href="pgls.html#practicals" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>There are several ways to run a PGLS in R. For instance, the package <code>caper</code> is a very well known package for PGLS. However, we will use the function <code>gls</code> here from the <code>nlme</code> package. This function is robust and has the advantage to be very flexible. Indeed, it allows to easily use more complex models such as mixed effect models, although this will not be discussed here.</p>
<p>Before we run the PGLS, let’s run the basic model with the function <code>gls</code> as a reference. Running the standard linear model with the package <code>nlme</code> will allow to run model comparison functions in R (see below), which would not be possible is different models were fitted using different packages.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="pgls.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(nlme)</span>
<span id="cb23-2"><a href="pgls.html#cb23-2" aria-hidden="true" tabindex="-1"></a>shade.pgls0 <span class="ot">&lt;-</span> <span class="fu">gls</span>(Shade <span class="sc">~</span> Wd, <span class="at">data =</span> seedplantsdata)</span>
<span id="cb23-3"><a href="pgls.html#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(shade.pgls0)</span></code></pre></div>
<pre><code>## Generalized least squares fit by REML
##   Model: Shade ~ Wd 
##   Data: seedplantsdata 
##       AIC     BIC    logLik
##   180.472 186.494 -87.23602
## 
## Coefficients:
##               Value Std.Error  t-value p-value
## (Intercept) 2.00098 0.7500707 2.667722  0.0100
## Wd          1.81296 1.5675668 1.156544  0.2525
## 
##  Correlation: 
##    (Intr)
## Wd -0.979
## 
## Standardized residuals:
##         Min          Q1         Med          Q3         Max 
## -1.63307700 -0.89457443  0.04911902  0.61207032  2.07940955 
## 
## Residual standard error: 1.145813 
## Degrees of freedom: 57 total; 55 residual</code></pre>
<p>You can see that the output is essentially identical to that of the <code>lm</code> function. However, there are some differences. One is the presence of the item “Correlation:” that gives the correlation among the estimated parameters. Also, the “Standardized residuals” are the raw residuals divided by the residual standard error (the raw residuals can be output with <code>residuals(shade.gls,"response")</code>).</p>
<p>Now, let’s run a PGLS model. To assign the correlation matrix to the <code>gls</code> function, you simply need to use the <code>corr</code> option of the <code>gls</code> function. However, you need to use a specific correlation function so that R understands that it is a correlation matrix and estimate the model correctly.</p>
<p>There are several different types of correlation structures that are available in <code>R</code>. We will start by using one of the simplest one, called <code>corSymm</code>, that assumes that the correlation matrix is symmetric. This is the case with phylogenetic trees; the correlation between species <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> is the same as between <span class="math inline">\(b\)</span> ad <span class="math inline">\(a\)</span>. Only the lower triangular part of the matrix has to be passed to the <code>corSymm</code> structure. If <code>mat</code> is the correlation matrix, this is done using the command <code>mat[lower.tri(mat)]</code>. Then you pass the correlation matrix to <code>gls</code> using the <code>correlation</code> argument.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="pgls.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the correlation matrix from the tree</span></span>
<span id="cb25-2"><a href="pgls.html#cb25-2" aria-hidden="true" tabindex="-1"></a>mat <span class="ot">&lt;-</span> <span class="fu">vcv</span>(seedplantstree,<span class="at">corr=</span><span class="cn">TRUE</span>)</span>
<span id="cb25-3"><a href="pgls.html#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the correlation structure for gls</span></span>
<span id="cb25-4"><a href="pgls.html#cb25-4" aria-hidden="true" tabindex="-1"></a>corr.struct <span class="ot">&lt;-</span> <span class="fu">corSymm</span>(mat[<span class="fu">lower.tri</span>(mat)],<span class="at">fixed=</span><span class="cn">TRUE</span>)</span>
<span id="cb25-5"><a href="pgls.html#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the pgls</span></span>
<span id="cb25-6"><a href="pgls.html#cb25-6" aria-hidden="true" tabindex="-1"></a>shade.pgls1 <span class="ot">&lt;-</span> <span class="fu">gls</span>(Shade <span class="sc">~</span> Wd, <span class="at">data =</span> seedplantsdata, <span class="at">correlation=</span>corr.struct)</span>
<span id="cb25-7"><a href="pgls.html#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(shade.pgls1)</span></code></pre></div>
<pre><code>## Generalized least squares fit by REML
##   Model: Shade ~ Wd 
##   Data: seedplantsdata 
##        AIC      BIC    logLik
##   214.3762 220.3982 -104.1881
## 
## Correlation Structure: General
##  Formula: ~1 
##  Parameter estimate(s):
##  Correlation: 
##    1     2     3     4     5     6     7     8     9     10    11    12   
## 2  0.000                                                                  
## 3  0.000 0.967                                                            
## 4  0.000 0.967 0.976                                                      
## 5  0.000 0.967 0.981 0.976                                                
## 6  0.000 0.967 0.974 0.974 0.974                                          
## 7  0.000 0.967 0.997 0.976 0.981 0.974                                    
## 8  0.000 0.967 0.974 0.974 0.974 0.997 0.974                              
## 9  0.000 0.967 0.976 0.983 0.976 0.974 0.976 0.974                        
## 10 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654                  
## 11 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.984            
## 12 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.726 0.726      
## 13 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.952 0.952 0.726
## 14 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.952 0.952 0.726
## 15 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.952 0.952 0.726
## 16 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.945 0.945 0.726
## 17 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.876 0.876 0.726
## 18 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.876 0.876 0.726
## 19 0.000 0.596 0.596 0.596 0.596 0.596 0.596 0.596 0.596 0.596 0.596 0.596
## 20 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.726 0.726 0.989
## 21 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.835 0.835 0.726
## 22 0.000 0.596 0.596 0.596 0.596 0.596 0.596 0.596 0.596 0.596 0.596 0.596
## 23 0.000 0.596 0.596 0.596 0.596 0.596 0.596 0.596 0.596 0.596 0.596 0.596
## 24 0.000 0.596 0.596 0.596 0.596 0.596 0.596 0.596 0.596 0.596 0.596 0.596
## 25 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.876 0.876 0.726
## 26 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.876 0.876 0.726
## 27 0.528 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## 28 0.843 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## 29 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.726 0.726 0.983
## 30 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.945 0.945 0.726
## 31 0.860 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## 32 0.860 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## 33 0.860 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## 34 0.860 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## 35 0.860 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## 36 0.860 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## 37 0.860 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## 38 0.000 0.523 0.523 0.523 0.523 0.523 0.523 0.523 0.523 0.523 0.523 0.523
## 39 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.675 0.675 0.675
## 40 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.675 0.675 0.675
## 41 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.675 0.675 0.675
## 42 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.675 0.675 0.675
## 43 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.726 0.726 0.898
## 44 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.726 0.726 0.898
## 45 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.726 0.726 0.898
## 46 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.835 0.835 0.726
## 47 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.835 0.835 0.726
## 48 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.835 0.835 0.726
## 49 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.835 0.835 0.726
## 50 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.675 0.675 0.675
## 51 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.726 0.726 0.980
## 52 0.528 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## 53 0.000 0.720 0.720 0.720 0.720 0.720 0.720 0.720 0.720 0.654 0.654 0.654
## 54 0.906 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## 55 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.726 0.726 0.800
## 56 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.726 0.726 0.800
## 57 0.000 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.726 0.726 0.800
##    13    14    15    16    17    18    19    20    21    22    23    24   
## 2                                                                         
## 3                                                                         
## 4                                                                         
## 5                                                                         
## 6                                                                         
## 7                                                                         
## 8                                                                         
## 9                                                                         
## 10                                                                        
## 11                                                                        
## 12                                                                        
## 13                                                                        
## 14 0.998                                                                  
## 15 0.994 0.994                                                            
## 16 0.945 0.945 0.945                                                      
## 17 0.876 0.876 0.876 0.876                                                
## 18 0.876 0.876 0.876 0.876 0.998                                          
## 19 0.596 0.596 0.596 0.596 0.596 0.596                                    
## 20 0.726 0.726 0.726 0.726 0.726 0.726 0.596                              
## 21 0.835 0.835 0.835 0.835 0.835 0.835 0.596 0.726                        
## 22 0.596 0.596 0.596 0.596 0.596 0.596 0.715 0.596 0.596                  
## 23 0.596 0.596 0.596 0.596 0.596 0.596 0.715 0.596 0.596 0.997            
## 24 0.596 0.596 0.596 0.596 0.596 0.596 0.715 0.596 0.596 0.999 0.997      
## 25 0.876 0.876 0.876 0.876 0.984 0.984 0.596 0.726 0.835 0.596 0.596 0.596
## 26 0.876 0.876 0.876 0.876 0.984 0.984 0.596 0.726 0.835 0.596 0.596 0.596
## 27 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## 28 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## 29 0.726 0.726 0.726 0.726 0.726 0.726 0.596 0.983 0.726 0.596 0.596 0.596
## 30 0.945 0.945 0.945 0.988 0.876 0.876 0.596 0.726 0.835 0.596 0.596 0.596
## 31 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## 32 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## 33 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## 34 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## 35 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## 36 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## 37 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## 38 0.523 0.523 0.523 0.523 0.523 0.523 0.523 0.523 0.523 0.523 0.523 0.523
## 39 0.675 0.675 0.675 0.675 0.675 0.675 0.596 0.675 0.675 0.596 0.596 0.596
## 40 0.675 0.675 0.675 0.675 0.675 0.675 0.596 0.675 0.675 0.596 0.596 0.596
## 41 0.675 0.675 0.675 0.675 0.675 0.675 0.596 0.675 0.675 0.596 0.596 0.596
## 42 0.675 0.675 0.675 0.675 0.675 0.675 0.596 0.675 0.675 0.596 0.596 0.596
## 43 0.726 0.726 0.726 0.726 0.726 0.726 0.596 0.898 0.726 0.596 0.596 0.596
## 44 0.726 0.726 0.726 0.726 0.726 0.726 0.596 0.898 0.726 0.596 0.596 0.596
## 45 0.726 0.726 0.726 0.726 0.726 0.726 0.596 0.898 0.726 0.596 0.596 0.596
## 46 0.835 0.835 0.835 0.835 0.835 0.835 0.596 0.726 0.881 0.596 0.596 0.596
## 47 0.835 0.835 0.835 0.835 0.835 0.835 0.596 0.726 0.881 0.596 0.596 0.596
## 48 0.835 0.835 0.835 0.835 0.835 0.835 0.596 0.726 0.881 0.596 0.596 0.596
## 49 0.835 0.835 0.835 0.835 0.835 0.835 0.596 0.726 0.881 0.596 0.596 0.596
## 50 0.675 0.675 0.675 0.675 0.675 0.675 0.596 0.675 0.675 0.596 0.596 0.596
## 51 0.726 0.726 0.726 0.726 0.726 0.726 0.596 0.980 0.726 0.596 0.596 0.596
## 52 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## 53 0.654 0.654 0.654 0.654 0.654 0.654 0.596 0.654 0.654 0.596 0.596 0.596
## 54 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## 55 0.726 0.726 0.726 0.726 0.726 0.726 0.596 0.800 0.726 0.596 0.596 0.596
## 56 0.726 0.726 0.726 0.726 0.726 0.726 0.596 0.800 0.726 0.596 0.596 0.596
## 57 0.726 0.726 0.726 0.726 0.726 0.726 0.596 0.800 0.726 0.596 0.596 0.596
##    25    26    27    28    29    30    31    32    33    34    35    36   
## 2                                                                         
## 3                                                                         
## 4                                                                         
## 5                                                                         
## 6                                                                         
## 7                                                                         
## 8                                                                         
## 9                                                                         
## 10                                                                        
## 11                                                                        
## 12                                                                        
## 13                                                                        
## 14                                                                        
## 15                                                                        
## 16                                                                        
## 17                                                                        
## 18                                                                        
## 19                                                                        
## 20                                                                        
## 21                                                                        
## 22                                                                        
## 23                                                                        
## 24                                                                        
## 25                                                                        
## 26 0.992                                                                  
## 27 0.000 0.000                                                            
## 28 0.000 0.000 0.528                                                      
## 29 0.726 0.726 0.000 0.000                                                
## 30 0.876 0.876 0.000 0.000 0.726                                          
## 31 0.000 0.000 0.528 0.843 0.000 0.000                                    
## 32 0.000 0.000 0.528 0.843 0.000 0.000 0.874                              
## 33 0.000 0.000 0.528 0.843 0.000 0.000 0.985 0.874                        
## 34 0.000 0.000 0.528 0.843 0.000 0.000 0.997 0.874 0.985                  
## 35 0.000 0.000 0.528 0.843 0.000 0.000 0.874 0.965 0.874 0.874            
## 36 0.000 0.000 0.528 0.843 0.000 0.000 0.999 0.874 0.985 0.997 0.874      
## 37 0.000 0.000 0.528 0.843 0.000 0.000 0.874 0.926 0.874 0.874 0.926 0.874
## 38 0.523 0.523 0.000 0.000 0.523 0.523 0.000 0.000 0.000 0.000 0.000 0.000
## 39 0.675 0.675 0.000 0.000 0.675 0.675 0.000 0.000 0.000 0.000 0.000 0.000
## 40 0.675 0.675 0.000 0.000 0.675 0.675 0.000 0.000 0.000 0.000 0.000 0.000
## 41 0.675 0.675 0.000 0.000 0.675 0.675 0.000 0.000 0.000 0.000 0.000 0.000
## 42 0.675 0.675 0.000 0.000 0.675 0.675 0.000 0.000 0.000 0.000 0.000 0.000
## 43 0.726 0.726 0.000 0.000 0.898 0.726 0.000 0.000 0.000 0.000 0.000 0.000
## 44 0.726 0.726 0.000 0.000 0.898 0.726 0.000 0.000 0.000 0.000 0.000 0.000
## 45 0.726 0.726 0.000 0.000 0.898 0.726 0.000 0.000 0.000 0.000 0.000 0.000
## 46 0.835 0.835 0.000 0.000 0.726 0.835 0.000 0.000 0.000 0.000 0.000 0.000
## 47 0.835 0.835 0.000 0.000 0.726 0.835 0.000 0.000 0.000 0.000 0.000 0.000
## 48 0.835 0.835 0.000 0.000 0.726 0.835 0.000 0.000 0.000 0.000 0.000 0.000
## 49 0.835 0.835 0.000 0.000 0.726 0.835 0.000 0.000 0.000 0.000 0.000 0.000
## 50 0.675 0.675 0.000 0.000 0.675 0.675 0.000 0.000 0.000 0.000 0.000 0.000
## 51 0.726 0.726 0.000 0.000 0.980 0.726 0.000 0.000 0.000 0.000 0.000 0.000
## 52 0.000 0.000 0.918 0.528 0.000 0.000 0.528 0.528 0.528 0.528 0.528 0.528
## 53 0.654 0.654 0.000 0.000 0.654 0.654 0.000 0.000 0.000 0.000 0.000 0.000
## 54 0.000 0.000 0.528 0.843 0.000 0.000 0.860 0.860 0.860 0.860 0.860 0.860
## 55 0.726 0.726 0.000 0.000 0.800 0.726 0.000 0.000 0.000 0.000 0.000 0.000
## 56 0.726 0.726 0.000 0.000 0.800 0.726 0.000 0.000 0.000 0.000 0.000 0.000
## 57 0.726 0.726 0.000 0.000 0.800 0.726 0.000 0.000 0.000 0.000 0.000 0.000
##    37    38    39    40    41    42    43    44    45    46    47    48   
## 2                                                                         
## 3                                                                         
## 4                                                                         
## 5                                                                         
## 6                                                                         
## 7                                                                         
## 8                                                                         
## 9                                                                         
## 10                                                                        
## 11                                                                        
## 12                                                                        
## 13                                                                        
## 14                                                                        
## 15                                                                        
## 16                                                                        
## 17                                                                        
## 18                                                                        
## 19                                                                        
## 20                                                                        
## 21                                                                        
## 22                                                                        
## 23                                                                        
## 24                                                                        
## 25                                                                        
## 26                                                                        
## 27                                                                        
## 28                                                                        
## 29                                                                        
## 30                                                                        
## 31                                                                        
## 32                                                                        
## 33                                                                        
## 34                                                                        
## 35                                                                        
## 36                                                                        
## 37                                                                        
## 38 0.000                                                                  
## 39 0.000 0.523                                                            
## 40 0.000 0.523 0.959                                                      
## 41 0.000 0.523 0.964 0.959                                                
## 42 0.000 0.523 0.964 0.959 0.982                                          
## 43 0.000 0.523 0.675 0.675 0.675 0.675                                    
## 44 0.000 0.523 0.675 0.675 0.675 0.675 0.986                              
## 45 0.000 0.523 0.675 0.675 0.675 0.675 0.998 0.986                        
## 46 0.000 0.523 0.675 0.675 0.675 0.675 0.726 0.726 0.726                  
## 47 0.000 0.523 0.675 0.675 0.675 0.675 0.726 0.726 0.726 0.997            
## 48 0.000 0.523 0.675 0.675 0.675 0.675 0.726 0.726 0.726 0.997 0.999      
## 49 0.000 0.523 0.675 0.675 0.675 0.675 0.726 0.726 0.726 0.984 0.984 0.984
## 50 0.000 0.523 0.936 0.936 0.936 0.936 0.675 0.675 0.675 0.675 0.675 0.675
## 51 0.000 0.523 0.675 0.675 0.675 0.675 0.898 0.898 0.898 0.726 0.726 0.726
## 52 0.528 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## 53 0.000 0.523 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654 0.654
## 54 0.860 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## 55 0.000 0.523 0.675 0.675 0.675 0.675 0.800 0.800 0.800 0.726 0.726 0.726
## 56 0.000 0.523 0.675 0.675 0.675 0.675 0.800 0.800 0.800 0.726 0.726 0.726
## 57 0.000 0.523 0.675 0.675 0.675 0.675 0.800 0.800 0.800 0.726 0.726 0.726
##    49    50    51    52    53    54    55    56   
## 2                                                 
## 3                                                 
## 4                                                 
## 5                                                 
## 6                                                 
## 7                                                 
## 8                                                 
## 9                                                 
## 10                                                
## 11                                                
## 12                                                
## 13                                                
## 14                                                
## 15                                                
## 16                                                
## 17                                                
## 18                                                
## 19                                                
## 20                                                
## 21                                                
## 22                                                
## 23                                                
## 24                                                
## 25                                                
## 26                                                
## 27                                                
## 28                                                
## 29                                                
## 30                                                
## 31                                                
## 32                                                
## 33                                                
## 34                                                
## 35                                                
## 36                                                
## 37                                                
## 38                                                
## 39                                                
## 40                                                
## 41                                                
## 42                                                
## 43                                                
## 44                                                
## 45                                                
## 46                                                
## 47                                                
## 48                                                
## 49                                                
## 50 0.675                                          
## 51 0.726 0.675                                    
## 52 0.000 0.000 0.000                              
## 53 0.654 0.654 0.654 0.000                        
## 54 0.000 0.000 0.000 0.528 0.000                  
## 55 0.726 0.675 0.800 0.000 0.654 0.000            
## 56 0.726 0.675 0.800 0.000 0.654 0.000 0.983      
## 57 0.726 0.675 0.800 0.000 0.654 0.000 0.999 0.983
## 
## Coefficients:
##                Value Std.Error   t-value p-value
## (Intercept) 0.911433  4.409058 0.2067184  0.8370
## Wd          4.361028  1.693349 2.5753865  0.0127
## 
##  Correlation: 
##    (Intr)
## Wd -0.166
## 
## Standardized residuals:
##         Min          Q1         Med          Q3         Max 
## -0.26890642 -0.16431866 -0.02645422  0.09638984  0.34953444 
## 
## Residual standard error: 7.455109 
## Degrees of freedom: 57 total; 55 residual</code></pre>
<p>Note that the term <code>fixed=TRUE</code> in the corSymm structure indicates that the correlation structure is fixed during the parameter optimization.</p>
<p>The output is similar to that of the model without the correlation, except for the output of the correlation matrix.</p>
<p>Interestingly, you can see that the coefficient estimate for the slope is greater (4.361) than with standard regression and also significant (<span class="math inline">\(p\)</span>=0.0127). This is a positive example of PGLS. Indeed, the relationship between shade tolerance and wood density was obscured by the phylogenetic correlation of the residuals. Once this correlation is accounted for, the significant relationship is revealed.</p>
<p>A significant relationship between shade tolerance and wood density actually make sense, even though this relationship is most likely not causal. Indeed, shade tolerant trees are generally sucessional species and often grow slower, partly because of the limited light availability, and thus tend to develop higher density woods.</p>
<p>Now, let’s have a look at the residuals of the model. To extract residuals corrected by the correlation structure, you need to ask for the normalized residuals.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="pgls.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the residuals corrected by the correlation structure</span></span>
<span id="cb27-2"><a href="pgls.html#cb27-2" aria-hidden="true" tabindex="-1"></a>pgls1.res <span class="ot">&lt;-</span> <span class="fu">residuals</span>(shade.pgls1,<span class="at">type=</span><span class="st">&quot;normalized&quot;</span>)</span>
<span id="cb27-3"><a href="pgls.html#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Change the graphical parameters</span></span>
<span id="cb27-4"><a href="pgls.html#cb27-4" aria-hidden="true" tabindex="-1"></a>op <span class="ot">&lt;-</span> <span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb27-5"><a href="pgls.html#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Same plotting as above except for using pgls1.res as residuals</span></span>
<span id="cb27-6"><a href="pgls.html#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(seedplantstree,<span class="at">type=</span><span class="st">&quot;p&quot;</span>,<span class="cn">TRUE</span>,<span class="at">label.offset=</span><span class="fl">0.01</span>,<span class="at">cex=</span><span class="fl">0.5</span>,<span class="at">no.margin=</span><span class="cn">FALSE</span>)</span>
<span id="cb27-7"><a href="pgls.html#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tiplabels</span>(<span class="at">pch=</span><span class="dv">21</span>,<span class="at">bg=</span>cols[<span class="fu">ifelse</span>(pgls1.res<span class="sc">&gt;</span><span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>)],<span class="at">col=</span><span class="st">&quot;black&quot;</span>,</span>
<span id="cb27-8"><a href="pgls.html#cb27-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">cex=</span><span class="fu">abs</span>(pgls1.res),<span class="at">adj=</span><span class="fl">0.505</span>)</span>
<span id="cb27-9"><a href="pgls.html#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topleft&quot;</span>,<span class="at">legend=</span><span class="fu">c</span>(<span class="st">&quot;-2&quot;</span>,<span class="st">&quot;-1&quot;</span>,<span class="st">&quot;0&quot;</span>,<span class="st">&quot;1&quot;</span>,<span class="st">&quot;2&quot;</span>),<span class="at">pch=</span><span class="dv">21</span>,</span>
<span id="cb27-10"><a href="pgls.html#cb27-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">pt.bg=</span>cols[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">2</span>)],<span class="at">bty=</span><span class="st">&quot;n&quot;</span>,</span>
<span id="cb27-11"><a href="pgls.html#cb27-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">text.col=</span><span class="st">&quot;black&quot;</span>,<span class="at">cex=</span><span class="fl">0.8</span>,<span class="at">pt.cex=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">1</span>,<span class="fl">0.1</span>,<span class="dv">1</span>,<span class="dv">2</span>))</span></code></pre></div>
<p><img src="pcm-workshop_files/figure-html/pgls%20residual%20fit-1.png" width="672" /></p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="pgls.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reset graphical parameters to defaults</span></span>
<span id="cb28-2"><a href="pgls.html#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(op) </span></code></pre></div>
<p>If you compare with the ordinary least squares optimization, the residuals are much less phylogenetically correlated.</p>
<div id="other-correlation-structures" class="section level3 hasAnchor" number="5.3.1">
<h3><span class="header-section-number">5.3.1</span> Other correlation structures<a href="pgls.html#other-correlation-structures" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In the previous PGLS, we have used the corSymm structure to pass the phylogenetic correlation structure to the gls. This is perfectly fine, but there are more simple ways. Julien Dutheil has developped phylogenetic structures to be used especially in PGLS.</p>
<p>The one we used above is equivalent to the <code>corBrownian</code> structure of <code>ape</code>. This approach is easier and you just have to pass the tree to the correlation structure. Here is the same example using the <code>corBrownian</code> structure.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="pgls.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the correlation structure</span></span>
<span id="cb29-2"><a href="pgls.html#cb29-2" aria-hidden="true" tabindex="-1"></a>bm.corr <span class="ot">&lt;-</span> <span class="fu">corBrownian</span>(<span class="at">phy=</span>seedplantstree, <span class="at">form=</span><span class="sc">~</span><span class="fu">rownames</span>())</span>
<span id="cb29-3"><a href="pgls.html#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co"># PGLS</span></span>
<span id="cb29-4"><a href="pgls.html#cb29-4" aria-hidden="true" tabindex="-1"></a>shade.pgls1b <span class="ot">&lt;-</span> <span class="fu">gls</span>(Shade <span class="sc">~</span> Wd, <span class="at">data =</span> seedplantsdata, <span class="at">correlation=</span>bm.corr)</span>
<span id="cb29-5"><a href="pgls.html#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(shade.pgls1b)</span></code></pre></div>
<pre><code>## Generalized least squares fit by REML
##   Model: Shade ~ Wd 
##   Data: seedplantsdata 
##        AIC      BIC    logLik
##   214.3762 220.3982 -104.1881
## 
## Correlation Structure: corBrownian
##  Formula: ~rownames() 
##  Parameter estimate(s):
## numeric(0)
## 
## Coefficients:
##                Value Std.Error   t-value p-value
## (Intercept) 0.911433  4.409058 0.2067184  0.8370
## Wd          4.361028  1.693349 2.5753865  0.0127
## 
##  Correlation: 
##    (Intr)
## Wd -0.166
## 
## Standardized residuals:
##         Min          Q1         Med          Q3         Max 
## -0.26890642 -0.16431866 -0.02645422  0.09638984  0.34953444 
## 
## Residual standard error: 7.455109 
## Degrees of freedom: 57 total; 55 residual</code></pre>
<p>You can see that the results are identical. The only difference is that the correlation structure is not outputed in the summary. The <code>numeric(0)</code> means that no parameter was estimated during the optimization (it is fixed).</p>
<p>Now, you might wonder why the correlation structure is called corBrownian. This is because is uses Brownian motion to model the evolution along the branch of the tree. This is often refferred as a neutral model. If you want to know more about the Brownian Motion model, you can look at the section <a href="BM-model.html#BM-model">12</a> on this model.</p>
</div>
</div>
<div id="challenge-3" class="section level2 hasAnchor" number="5.4">
<h2><span class="header-section-number">5.4</span> Challenge 3<a href="pgls.html#challenge-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Fit a PGLS model to see whether the seed mass (<code>Sm</code>) explains shade tolerance (<code>Shade</code>) with the seedplantdataset. How does it compare to the results from the standard regression.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="linear-regression.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="pic.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/04-pgls.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["pcm-workshop.pdf", "pcm-workshop.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
